### ISSUE TITLE
Display issue when Symfony Translations not enabled.

### ISSUE THREAD

**Issue by realtyhub** [AliHichem/AliDatatableBundle#101]
There seems to be a problem if Symfony Translations are not enable. When I mean not enabled, for example if the following setting is missing from config.yml
```
framework:
    translator:      { fallback: "%locale%" }  
```

When the table is shown, you will see strings such as "ali.common.sLengthMenu" or "ali.common.sInfoali.common.sInfoPostFix" showing instead of the correct translation. 

This is easily fixed by the developer enabling translations, however without knowing this, the given bug can be miss leading and time consuming to debug. Perhaps some kind of warning to the developer that translations are not enabled would be useful?

Thanks

**Comment by AliHichem** [comment]
Thanks for letting me know about it !
