### ISSUE TITLE
Uncaught ReferenceError: $ is not defined - Script tag

### ISSUE THREAD

**Issue by jjamaral** [AliHichem/AliDatatableBundle#102]
Hi!

First of all, congratz for this bundle, its pretty cool!
However, i'm having troubles when initialise the table. I think its because generated script tag and code was included before jquery file declaration.

I mean:

<script type="text/javascript">
    $(document).ready(function(){
       ...
    });
</script>
<table class="display table table-bordered" id="ali-dta_c0c7c76d30bd3dcaefc96f40275bdc0a"> 
...
</table>
<script src="jquery.min.js" type="text/javascript"></script>

How can I include this code only before jquery and jquery.dataTables.js declaration? 
And its cool if this code was done in a single file, instead directly on script tag. Is it possible?

Thanks in advance.

Best regards,
João Amaral

**Comment by AliHichem** [comment]
Are you you did a copy/paste of the code you're having problems with ? I only see "..."

**Comment by AliHichem** [comment]
I'm closing this issue as the v2 is published and this problem should not happen anymore: now all the datatable configuration js code is automatically groupped, minified and moved to the bottom of the <body> element (exactly like the symfony profiler). Hope you like it !
