### ISSUE TITLE
Installation on Symfony 2.3.27

### ISSUE THREAD

**Issue by webkod3r** [AliHichem/AliDatatableBundle#109]
Hi there, I have the next problem when I try to install this bundle on Symfony 2.3.27. I've been tried with `dev-master` and with `@stable` tags. Both of them throws the same error:

### dev-master
php.exe C:\ProgramData\ComposerSetup\bin\composer.phar update ali/datatable
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove doctrine/cache v1.4.1
    - Conclusion: don't install doctrine/cache v1.4.1
    - doctrine/common 2.2.1 conflicts with doctrine/cache[v1.4.1].
    - doctrine/common 2.2.2 conflicts with doctrine/cache[v1.4.1].
    - doctrine/common 2.2.3 conflicts with doctrine/cache[v1.4.1].
    - doctrine/common 2.3.0 conflicts with doctrine/cache[v1.4.1].
    - Installation request for doctrine/cache == 1.4.1.0 -> satisfiable by doctrine/cache[v1.4.1].
    - Installation request for ali/datatable dev-master -> satisfiable by ali/datatable[dev-master].
    - Conclusion: don't install doctrine/common v2.5.0|install doctrine/common 2.2.1|install doctrine/common 2.2.2|install doctrine/common 2.2.3|install doctrine/common 2.3.0
    - Conclusion: remove doctrine/common v2.5.0|install doctrine/common 2.2.1|install doctrine/common 2.2.2|install doctrine/common 2.2.3|install doctrine/common 2.3.0
    - ali/datatable dev-master requires doctrine/common >=2.1,<2.4.x-dev -> satisfiable by doctrine/common[2.1.3, 2.1.4, 2.2.0, 2.2.1, 2.2.2, 2.2.3, 2.3.0, v2.4.0, v2.4.1, v2.4.2].
    - Can only install one of: doctrine/common[v2.4.0, v2.5.0].
    - Can only install one of: doctrine/common[v2.4.1, v2.5.0].
    - Can only install one of: doctrine/common[v2.4.2, v2.5.0].
    - Can only install one of: doctrine/common[2.1.3, v2.5.0].
    - Can only install one of: doctrine/common[2.1.4, v2.5.0].
    - Can only install one of: doctrine/common[2.2.0, v2.5.0].
    - Installation request for doctrine/common == 2.5.0.0 -> satisfiable by doctrine/common[v2.5.0].

### @stable
php.exe C:\ProgramData\ComposerSetup\bin\composer.phar update ali/datatable
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install ali/datatable v1.4.1
    - Conclusion: don't install ali/datatable v1.4.0
    - Conclusion: don't install ali/datatable v1.3.3
    - Conclusion: remove doctrine/cache v1.4.1
    - Conclusion: don't install doctrine/cache v1.4.1
    - doctrine/common 2.2.1 conflicts with doctrine/cache[v1.4.1].
    - doctrine/common 2.2.2 conflicts with doctrine/cache[v1.4.1].
    - doctrine/common 2.2.3 conflicts with doctrine/cache[v1.4.1].
    - doctrine/common 2.3.0 conflicts with doctrine/cache[v1.4.1].
    - Conclusion: don't install doctrine/common v2.5.0|install doctrine/common 2.2.1|install doctrine/common 2.2.2|install doctrine/common 2.2.3|install doctrine/common 2.3.0
    - Installation request for doctrine/cache == 1.4.1.0 -> satisfiable by doctrine/cache[v1.4.1].
    - Installation request for ali/datatable @stable -> satisfiable by ali/datatable[v1.3.2, v1.3.3, v1.4.0, v1.4.1].
    - Conclusion: remove doctrine/common v2.5.0|install doctrine/common 2.2.1|install doctrine/common 2.2.2|install doctrine/common 2.2.3|install doctrine/common 2.3.0
    - ali/datatable v1.3.2 requires doctrine/common >=2.1,<2.4-dev -> satisfiable by doctrine/common[2.1.3, 2.1.4, 2.2.0, 2.2.1, 2.2.2, 2.2.3, 2.3.0].
    - Can only install one of: doctrine/common[2.1.3, v2.5.0].
    - Can only install one of: doctrine/common[2.1.4, v2.5.0].
    - Can only install one of: doctrine/common[2.2.0, v2.5.0].
    - Installation request for doctrine/common == 2.5.0.0 -> satisfiable by doctrine/common[v2.5.0].

This is my `composer.json` file:
```javascript
"require": {
        "php": ">=5.3.3",
        "symfony/symfony": "2.3.*",
        "doctrine/orm": "~2.2,>=2.2.3,<2.5",
        "doctrine/dbal": "<2.5",
        "doctrine/doctrine-bundle": "~1.2",
        "twig/extensions": "1.0.*",
        "symfony/assetic-bundle": "~2.3",
        "symfony/swiftmailer-bundle": "~2.3",
        "symfony/monolog-bundle": "~2.4",
        "sensio/distribution-bundle": "~2.3",
        "sensio/framework-extra-bundle": "~3.0,>=3.0.2",
        "sensio/generator-bundle": "~2.3",
        "incenteev/composer-parameter-handler": "~2.0",

      "friendsofsymfony/user-bundle": "~2.0@dev",
      "friendsofsymfony/jsrouting-bundle": "@stable",
      "doctrine/doctrine-fixtures-bundle": "2.2.*@dev",
      "ali/datatable": "dev-master"
    },
```

I'm using a fresh installation of Symfony2 with FOSUSerBundle and DoctrineFixtures only. How can I solve this problem??

Thanks in advance
WK

**Comment by AliHichem** [comment]
Hi, That's because symfony2 updated their requirements to support doctrine/orm > 2.4 and < 2.5. I just did the update too so now you should be able to install it using the master branch.

Regards !
