### ISSUE TITLE
Select the Properties of an Entity that are Foreign Keys of that table. 

### ISSUE THREAD

**Issue by Redjan** [AliHichem/AliDatatableBundle#112]
Hi,  i'm having this problem. When i want to select a field from an entity, and that field is a Foreign Key in that table, i get this error:

ContextErrorException: Notice: Undefined index: priority in C:\wamp2\www\crmba_prod\vendor\ali\datatable\Ali\DatatableBundle\Util\Factory\Query\DoctrineBuilder.php line 236

And the table shows 0 results. 

The query:

 return $this->get('datatable')
            //->setEntityManager($em)                                         // Optional
            ->setEntity("BackendadminBundle:Activity", "a")          // Replace "XXXMyBundle:Entity" by your entity
            ->setFields(
                array(
                    "Created At"    => 'a.createdAt',
                    "Updated At"    => 'a.updatedAt',
                    "Start Activity"=> 'a.startActivity',
                    "End Activity"  => 'a.endActivity',
                    "Description"   => 'a.activityDescription',
                    "Start Event"   => 'a.startEvent',
                    "End Event"     => 'a.endEvent',
                    "Note"          => 'a.note',
                    "Successful"    => 'a.issuccessful',
                    "Priority"      => 'a.priority',  ///// The FOREIGN KEY /////
                    "_identifier_"  => 'a.id')                              // you have to put the identifier field without label. Do not replace the "_identifier_"
            )
            //->addJoin('a.Actionresult', 'ar', \Doctrine\ORM\Query\Expr\Join::INNER_JOIN)
            //->setOrder("x.created", "desc")                               // it's also possible to set the default order
            ->setHasAction(true)
            ->setSearch(TRUE);          

Pleas, help me. 
Thank you in advance.

**Comment by j0ssGZ** [comment]
I think the "_identifier_" field should not rename it to "identifier".

**Comment by jinxboy13** [comment]
same Problem on all relational fields on symfony2.7

**Comment by AliHichem** [comment]
You get this error because you are trying to get the field "priority" from the wrong entity, you should set priority like this 
```
"Priority" => 'ar.priority', ///// The FOREIGN KEY /////
```
instead of what you did 
```
"Priority" => 'a.priority', ///// The FOREIGN KEY /////
```
