### ISSUE TITLE
Datatables 1.10 compatibility

### ISSUE THREAD

**Issue by Noles** [AliHichem/AliDatatableBundle#116]
AliDatatableBundle should be updated for DataTables >1.10.

**Comment by AliHichem** [comment]
I'm working on the v2 which will be updated to latest datatable version along with jQuery and bootstrap theme and bottom js integration and maybe mongodb support

**Comment by AliHichem** [comment]
v2 is pulished , now alidatatable is compatible with Datatable 1.10
