### ISSUE TITLE
Main Template

### ISSUE THREAD

**Issue by Cyr69** [AliHichem/AliDatatableBundle#118]
Hello,

I use main_template for custom the presentation of datatable but with your new release AliDatatable, I have this error : 
>Datatables warning: table id=dta-all - Cannot reinitialise Datatable. For more information about this error, please see http://datatables.net/tn/3

How can I use my current theme with your new release?

Thank you :)

Best Regards

**Comment by Cyr69** [comment]
Pending a correction, I return to the version 1.4. It OK :)
For info, the problem persists for DoctrineBuilder.php in v1.4 (cf. LinkedIn)

**Comment by pbeliberty** [comment]
I'm still with this error... Is there another solution than the return to the 1.4  ?

**Comment by AliHichem** [comment]
@Cyr69 @pbeliberty   "How can I use my current theme with your new release?" the v2 does only come with bootstrap theme, custom themes with the v2 are neither supported nor tested as mentioned in the readme file of this bundle. You can still use them at your own risk and if you encounter problems with custom theme in the bootstrap version then this out of support and related issues won't be treated.
