### ISSUE TITLE
Style error

### ISSUE THREAD

**Issue by JoseFanjul** [AliHichem/AliDatatableBundle#119]
Hello , first I want to congratulate and thank you for your work.

I am currently in development of a project using Symfony and after installing the bundle works well with 1.4v .

The problem is that when downloading assets by composer , including any CSS ( or the original datatable ) not shows me the controls correctly .

In the picture it is clear:

![issue](https://cloud.githubusercontent.com/assets/6393898/8797914/0a1992e4-2f9f-11e5-9b80-019dd0a47bf3.PNG)

Greetings and thank you

**Comment by AliHichem** [comment]
As far as I see from your screenshot it's just a translation issue : by default this bundle show any of its label by getting the related text from the translation dictionaries so I'm gonna guess that if I see labels like "ali.common...." that the translation is not enabled in your project. By enabling it your problem should be solved.

The v.1.4  comes with its assets meaning you can check the assets versions from this bundle to see if they fits well with yours. I didn't make assets version something manageable by composer as I don't see the need of it plus it gives the developer the ability to use different assets version if he want to ... this said , it's recommended to use the assets that comes with this bundle.

One last thing the V2 is already up and uses the latest version of twitter bootstrap , you should give it a try :).

**Comment by JoseFanjul** [comment]
Thank you very much for the response! First I tried install the 2.0v but got the error:

FatalErrorException: Error: Call to undefined method Symfony\Component\HttpKernel\Event\FilterResponseEvent::isMasterRequest() in ...

I think it is because some version of another unit (use Symfony 2.2.11 stand). I try to run it with the translation and I mention something.

A greeting!

**Comment by AliHichem** [comment]
The v2 is tested with sf2.7 , I should add that in the composer requirements.. thanks for letting me know about that !

**Comment by JoseFanjul** [comment]
I just tested and it works perfectly. Thank you very much, I will try to test the v2.0 when migrate my project to sf 2.7.


thank you!
