### ISSUE TITLE
Spanish language issue

### ISSUE THREAD

**Issue by webkod3r** [AliHichem/AliDatatableBundle#120]
Hi, I'm using the bundle with Spanish translation, but there are some words that have missing letters. For example: 
* 'No se encontr ninguna entrada' instead of 'No se encontr**ó** ninguna entrada'
* 'ltima' instead of '**Ú**ltima'

All words with accented characters are affected.

I'm using my own translation, but for other users this could be useful.

Thanks.

**Comment by rigobertocontreras** [comment]
Hello @webkod3r  did you find a solution??

**Comment by AliHichem** [comment]
@webkod3r , the Spanish translation was generated the first time using the classic google translator. As far a I remember there were some contributions to fix it that happened later on from native Spanish speakers which I really appreciate their help. 

As I only speak 3 languages (not including Spanish) , I'm afraid that I need more contribution from native Spanish speakers to fix this issue. 

I'm always open to any contribution so I invite you guys to make pull request with the fixed translation language in it.

Regards !

**Comment by webkod3r** [comment]
Ok, I'll make a fork, fix the translation and create the pull request to improve the bundle.

Greetings!!!

**Comment by webkod3r** [comment]
Ready I create the PR #126 with the fix for that. Thanks for let me help.

**Comment by AliHichem** [comment]
Thank you very much @webkod3r !
