### ISSUE TITLE
Return JsonResponse instead of Response for Util/Datatable

### ISSUE THREAD

**Issue by zgoniaiko** [AliHichem/AliDatatableBundle#136]
I suggest to return `JsonResponse` instead of `Response` [there](https://github.com/AliHichem/AliDatatableBundle/blob/master/Util/Datatable.php#L163).

It will look like

```
return new JsonResponse($output);
```

I can prepare pull for it in case it is acceptable.

**Comment by AliHichem** [comment]
This is indeed a good suggestion ! Feel free to contribute and I'll accept your pull request
