### ISSUE TITLE
data from two unrelated entities with common fields

### ISSUE THREAD

**Issue by greg606** [AliHichem/AliDatatableBundle#138]
HI, 
Is it possible at all to prepare data from two unrelated entities?

**Comment by AliHichem** [comment]
If you can do it with doctrine query builder than you can do it with this bundle.

**Comment by AliHichem** [comment]
would you mind giving us an example of what query you're trying to create ?

**Comment by greg606** [comment]
Like, two Coaches and Instructors with similar fields - i guess query cannot be used for that, that's the case.

**Comment by AliHichem** [comment]
A code example would be more helpful I have to say. Also, I still don't get your idea but from your description even with regular doctrine query it can't be done .

**Comment by AliHichem** [comment]
@greg606 I see a lot of issues you opened with no or very brief description which I'll close with no exceptions. Any new issue that you open with no description will not be treated.
