### ISSUE TITLE
phpspec for controller

### ISSUE THREAD

**Issue by greg606** [AliHichem/AliDatatableBundle#139]
I try to write spec for your use example but I'm stuck with this line:

```php 
$datatable->getQueryBuilder()->setDoctrineQueryBuilder($qb);
```

In my spec I have 

```php
$datatable->getQueryBuilder()->willReturn($dataTableQueryBuilder);
```
it gives me:
```
Error: Argument 1 passed to Double\Ali\DatatableBundle\Util\Factory\Query\DoctrineBuilder\P20::setDoctrineQueryBuilder()
      must be an instance of Doctrine\ORM\QueryBuilder, null given, called in
```

maybe some tried to write spec for it?

**Comment by AliHichem** [comment]
If you don't declare the the query builder variable before using than it make perfect sense to get this error , you should instantiate your query builder variable like mentioned in the readme file
```
$qb = $datatable->getQueryBuilder()->getDoctrineQueryBuilder(); 
```
