### ISSUE TITLE
Merge data from two fields.

### ISSUE THREAD

**Issue by tomwoj6** [AliHichem/AliDatatableBundle#143]
Is there any possibility to merge data from 2 fields from db into one field in datatables?
Something like that:

     ->setFields(
         array(
                  "fielddt" => 'field_db_1 + field_db_2',
                   "_identifier_" => 'vac.id')                          
            )

Ofcourse I can achieve this using querybuilder:

     $qb->from("BSHrBundle:Vac", "vac")
           ->leftJoin('x.author', 'author')  
           ->select('x')
           ->addSelect("CONCAT(x.firstname, ' ', x.lastname) as fullUsername");

     $datatable = $this->get('datatable')
                        ->setFields(
                                array(
                                    "Column 1 label" => 'fullUsername',
                                    "_identifier_" => 'vac.id')
                                )
                        ->setHasAction(FALSE)
                        ->setSearch(TRUE);
      $datatable->getQueryBuilder()->setDoctrineQueryBuilder($qb);

but later I can't search by that field. 
I am getting this error:
<code>[Syntax Error] line 0, col 82: Error: Expected '.' or '(', got 'fullUsername' </code>

Thanks in advance.

**Comment by AliHichem** [comment]
@tomwoj6  use dt_obj as described in https://github.com/AliHichem/AliDatatableBundle#-custom-renderer
