### ISSUE TITLE
Added ability to place filters at top and in dropdowns

### ISSUE THREAD

**Issue by RyanONeill1970** [AliHichem/AliDatatableBundle#148]
I would put a pull request in, but my environment was set for crlf and not lf so it is a little messy.

If you would like this patch then let me know and I'll get round to cleaning it up.

See https://github.com/RyanONeill1970/AliDatatableBundle/commit/225ab10b6f7fb63ba56a4c3264a283fe5f07ea90

**Comment by AliHichem** [comment]
Any contribution is well appreciated, in your case I see a lot of changes would you mind describing each one of them ? (closing this issue as this is not a real issue plus you can contact me directly via email if you want)
