### ISSUE TITLE
Suggestion: Add some things

### ISSUE THREAD

**Issue by bnd170** [AliHichem/AliDatatableBundle#150]
Until now it was using the bundle of Stwe (https://github.com/stwe/DatatablesBundle) but I have been limited since this bundle does not allow custom querys simply lets take a table and their relationships. And that's a serious limitation since I don't always need to get a whole table, sometimes we need some filters.

So I decided to find another bundle that integrates Symfony2 with DataTables jQuery plugin.

I found yours and I wonder if you can you implement a number of improvements.

### Field types.

This is something to consider as when to use your bundle can not be displayed, eg date directly, create a custom view when there are many data types that are very generic, eg datetime, boolean, array values, etc.

### Count relationships

Sometimes the client requests that a table of an entity related to another in of many-to-many relationship, requests to show the total of related records.

An example would be:

Users Table:
- Id
- Username
- Email
- Created at
- Groups
  - This field must to be a COUNT() of the related field groups in User entity.

¿Exists a way to do it whit the actual version?

### Conditional on actions:

Sometimes we need to hide or show action buttons depending on a value or set of values ​​from the registry.

For example if we want to add a button to show or hide a blog we could put a custom button, depending on the 'visible' field of the record, would show the action of 'show' or 'hide'.

Otherwise I quite like the bundle allows better customization than other bundles I've tried, congratulations.

**Comment by AliHichem** [comment]
@bnd170 The fields type and count of assocs might be part of the future improvements but they will for sure have low priority as they tend to go off the purpose of this project which is a simple symfony/doctrine integration with jQuery datatable, all the js customization or specefic rendering are not part of our consern and instead we let everyone use their custom renderers and implement their own js as everyone of us has their own "needs".

We tend to do more backend integration like a mongodb driver (half ready now) and maybe an elasticsearch driver in the future.

**Comment by zgoniaiko** [comment]
@bnd170 please check if you can use [DoctrineExtensions bundle](https://github.com/beberlei/DoctrineExtensions/blob/master/src/Query/Mysql/Field.php).

Expected it will allow you to use `FIELD` type (and a lot of other types) in DQL.

About `COUNT` for related entries, I think sub-query is way to go.

**Comment by bnd170** [comment]
@AliHichem thanks for your soon response, this issue is just for suggest you to improve your bundle :)

@zgoniaiko How can i make a subquery to count the relationship?

**Comment by zgoniaiko** [comment]
@bnd170 you can count relationship [like they do](http://blog.mdnsolutions.com/index.php/select-subquery-with-count-in-doctrine-dql/)
