### ISSUE TITLE
[Suggestion] Add integration with Sensio Insight

### ISSUE THREAD

**Issue by zgoniaiko** [AliHichem/AliDatatableBundle#151]
Add integration with [Sensio Insight](https://insight.sensiolabs.com/)

It can analyse code against multiple checkpoints. It will send notification in case security issues appear in this bundle or in bundle's dependencies.

Also it is free for open-source projects.

**Comment by AliHichem** [comment]
@zgoniaiko thank you for the advice ! I wish I could but unfortunately I couldn't , I tried to signup with two different email addresses and the same story happens: I get the confirmation email and I see a confirmation message saying I'm allowed to login but I'm not, I try many times and nothing happens I reset my password and when I get the reset password email and I visit the link guess what happen ... a 404 page lol  ( I just received it now , you can try and visit it and you'll see by yourself 
https://connect.sensiolabs.com/forgot-password/mazgamncw80gkwkw0ow4s80o40w44sk )

I remember trying to sign up before and I was disappointed from that rubbish website, to be honest I don't expect much from them after all ..

**Comment by AliHichem** [comment]
I just receied a second password rest email with the right link , finally !!
I'll give it a try , thanks @zgoniaiko  !
