### ISSUE TITLE
Multiple queries for the gridAction

### ISSUE THREAD

**Issue by sfauch1** [AliHichem/AliDatatableBundle#155]
Hi !

I have a question regarding your wonderful bundle. When I look in the Symfony profiler I always see 3 queries executed for the grid action.

One to get the count of records (I understand this one)
Two to get the records for the datatable (I don't understand that part) 

The first query seems to fetch more columns than the second one but they both return the exact same amount of records specified by the iDisplayLength option (50).

Any ideas why ?

Any hints will be appreciated.

Thanks

**Comment by sfauch1** [comment]
Thanks for fixing this @AliHichem

**Comment by AliHichem** [comment]
You're welcome !
