### ISSUE TITLE
DocBlocks @param "type"

### ISSUE THREAD

**Issue by rufinus** [AliHichem/AliDatatableBundle#161]
Nothing big...

You sometimes use type in the docblocks, which messes up IDE and QuodeQuality analyzers. as type is interpreted as a object which could not be resolved.

for a example see https://github.com/AliHichem/AliDatatableBundle/blob/master/Util/Datatable.php#L295   

this should be changed to `@param string`

Scrutinizer displays it like:
![scrutinizer](https://cloud.githubusercontent.com/assets/343160/12083351/e04fba7a-b2a1-11e5-8980-fe9ae0d5a5f3.png)

If i find time this week i submit a pull request.

**Comment by AliHichem** [comment]
Just merged your pull request, thanks @rufinus !
