### ISSUE TITLE
Displaying non database backed methods in a datatable

### ISSUE THREAD

**Issue by maxmumford** [AliHichem/AliDatatableBundle#175]
I have a doctrine entity called Property with the following database backed text fields:

- address1
- address2
- town
- postcode

I have added the following method to my Property entity to show a more readable address:

```
public function getAddressFriendly(){
    return $this->address1 . ', ' . $this->address2 . ', ' . $this->town . ', ' . $this->postcode;
}
```

How can I add a column to my datatable to show the getAddressFriendly method instead of having 4 separate columns each showing one of it's constituent address fields?

Max

**Comment by tontonDuPirox** [comment]
Same problem for me.

I've solve this problem for my project, you can look here for my solution : http://pastebin.com/tWteL4G7
I've created another DoctrineBuilder class extending the AliDatatableBundle one and modified the getData function. The overrided part is located lines 98-101.

Then, I've added the following line on my config.yml file:

```
parameters:
    datatable.class: MyBundle\Bundle\CoreBundle\Datatable\Datatable
```

I think this is a clean way for overring but comments are welcome.
You can look here for more informations on overriding: http://symfony.com/doc/current/cookbook/bundles/override.html

**Comment by maxmumford** [comment]
Hi @tontonDuPirox ,

Thanks for your contribution. I actually decided to go a different route in the end so this issue isn't relevant to me anymore.

I'll close the issue but hopefully your code snippet will be indexed for other people to find in the future.

Thanks
Max
