### ISSUE TITLE
Datatable name problem

### ISSUE THREAD

**Issue by lk77** [AliHichem/AliDatatableBundle#177]
hello, 

in the twig extension, a hash of a random number is used as id, and i'm asking if it can be better to use the data source instead :

`$options['id'] = 'ali-dta_' . md5($options['js']['sAjaxSource']);`

instead of

`$options['id'] = 'ali-dta_' . md5(rand(1, 100));`

A random id is incompatible with bStateChange, because the id change between loads, and the state can't be reloaded. If the sAjaxSource property is the same, it's most likely the same datatable, so each datatable has an unique id.

thanks

**Comment by AliHichem** [comment]
Hi,

Using the entity name as entry for the hash function could fire a bug if a user uses two datatable of the same entity and in the same page so we definitely should avoid that.

Thanks

**Comment by lk77** [comment]
Hi,
it's not the entity name, but the data source and each datatable should have a different data source
