### ISSUE TITLE
How to access the entity in Custom renderer

### ISSUE THREAD

**Issue by jonben** [AliHichem/AliDatatableBundle#50]
I am following the Custom renderer exemple in the doc with PHP Closures, I created the _grid_entity.html.twig and can display the $value of the specific column.

->setRenderer(
                    function(&$data) use ($controller_instance)
                    {
                        foreach ($data as $key => $value)
                        {
                            if ($key == 1)                                      // 1 => adress field
                            {
                                $data[$key] = $controller_instance
                                        ->get('templating')
                                        ->render(
                                               'XXXMyBundle:Module:_grid_entity.html.twig', 
                                               array('data' => $value)
                                        );
                            }
                        }
                    }
                )

In your exemple, you send $value, the value of that a specific column.
How can I access the whole entity object and send it to the template here?

In fact, I would like to display in a column several field values of the row, including the number of associated elements in a OneToMany collection, something like {{ entity.units.count }}.

In the image in your exemple, the "Information" column contains the value of 4 different fields, how do you achieve that?
![sample_02](https://f.cloud.github.com/assets/2309296/824135/1ac2c4a0-f039-11e2-904b-e4f33558e737.png)

**Comment by rufinus** [comment]
how would you access dt_obj in a closure in setRenderer() ?
