### ISSUE TITLE
Group By

### ISSUE THREAD

**Issue by johnwolf62** [AliHichem/AliDatatableBundle#62]
Hi, 
How do uses fields aliases and Grouping in the following example :+1: 
I want to display in Datatable then result of the Query Sql : 
Select count(*) as nmb, cityCode group by cityCode 
have coded the DQL which works fine) but I dont see how to do with datatable.

$qbTable = $this->get('datatable')
                ->setFields(
                    array(
                        "Number"          => 'nmb',
                        "CityCode"        => 'cityCode'
                   )
                  setGroupBy('a.cityCode');

Thanks.

JohnWolf

**Comment by apatkinson** [comment]
Was there an update to providing `groupBy` support?
