### ISSUE TITLE
Styling view using Twitter Bootstrap 3

### ISSUE THREAD

**Issue by paquitodev** [AliHichem/AliDatatableBundle#96]
I'm developing a application where I'm using Twitter Bootstrap 3.2 and I'll like to keep all the design in the same style. You bundle, until now, works fine but as I said before I'll like to render views using Bootstrap instead your style. [Here][1] is a example where the same people behind DataTables do it, it's possible in your bundle? How?

PS: I'll like also know the possibility to change the edit/delete names for icons from FontAwesome

 [1]: http://www.datatables.net/manual/styling/bootstrap-simple.html

**Comment by AliHichem** [comment]
Indeed this is something quite important to add, I add this for future updates. Although updates might take quite long sometimes , if you really want to have bootstrap layout it's really easy to add it by doing an override . If you're interested I can give you a hint about how to do it but I'm sure you already know how ^^.

**Comment by AliHichem** [comment]
V2 is published , now alidatatable is compatible with twitter bootstrap 3 (and only with 3 ^^)
