### ISSUE TITLE
data not display

### ISSUE THREAD

**Issue by habibun** [AliHichem/AliDatatableBundle#99]
controller:
/**
     * set datatable configs
     *
     * @return \Ali\DatatableBundle\Util\Datatable
     */
    private function _datatable()
    {
        return $this->get('datatable')
            ->setEntity("AcmePurchaseBundle:Purchase", "x")                          // replace "XXXMyBundle:Entity" by your entity
            ->setFields(
                array(
                    "Name"          => 'x.id',                        // Declaration for fields:
                    "Address"        => 'x.id',                    //      "label" => "alias.field_attribute_for_dql"
                    "_identifier_"  => 'x.id')                          // you have to put the identifier field without label. Do not replace the "_identifier_"
            )

            ->setHasAction(true);                                           // you can disable action column from here by setting "false".
    }

    /**
     * Grid action
     * @return Response
     */
    public function gridAction()
    {
        return $this->_datatable()->execute();                                      // call the "execute" method in your grid action
    }

    /**
     * Lists all entities.
     * @return Response
     */
    public function purchaseListAction()
    {
        $this->_datatable();                                                        // call the datatable config initializer
        return $this->render('AcmePurchaseBundle:Purchase:purchaseList.html.twig');                 // replace "XXXMyBundle:Module:index.html.twig" by yours
    }

routing:
purchase_list:
    pattern:  /purchase-list
    defaults: { _controller:  "AcmePurchaseBundle:Purchase:purchaseList"  }

ajax_purchase_list:
    pattern:  /ajax-purchase-list
    defaults: { _controller:  "AcmePurchaseBundle:Purchase:grid"  }

view:
{% extends '::base.html.twig' %}

{% block title %}Purchase-List{% endblock %}

{% block stylesheets %}
    <link href="{{ asset('bundles/alidatatable/css/demo_table.css') }}" type="text/css" rel="stylesheet" />
    <link href="{{ asset('bundles/alidatatable/css/smoothness/jquery-ui-1.8.4.custom.css') }}" type="text/css" rel="stylesheet" />
{% endblock %}

{% block body %}
    {{ datatable({
    'edit_route' : 'purchase_edit',
    'delete_route' : 'purchase_delete',
    'js' : {
    'sAjaxSource' : path('ajax_purchase_list')
    }
    })
    }}
{% endblock %}

{% block javascripts %}
    <script type="text/javascript" src="{{ asset('bundles/alidatatable/js/jquery.js') }}"></script>
    <script type="text/javascript" src="{{ asset('bundles/alidatatable/js/jquery.datatable.inc.js') }}"></script>
    <script type="text/javascript" src="{{ asset('bundles/alidatatable/js/jquery.dataTables.min.js') }}"></script>

    <script>
        $(document).ready(function(){
            $('#ali-dta_a3f390d88e4c41f2747bfa2f1b5f87db').DataTable();
        });
    </script>
{% endblock %}

data not render:see error
![untitled](https://cloud.githubusercontent.com/assets/5810350/5372269/49c5f894-8070-11e4-8906-29608f617f2c.png)

**Comment by AliHichem** [comment]
from a first look I see something you shouldn't do which is :
```
{% block javascripts %}
<script>
    $(document).ready(function(){
        $('#ali-dta_a3f390d88e4c41f2747bfa2f1b5f87db').DataTable();
    });
</script>
{% endblock %}
```
That piece of code is to remove.

The initialization of the datatable is done from the twig extension call which you already did in
```
{{ datatable({
'edit_route' : 'purchase_edit',
'delete_route' : 'purchase_delete',
'js' : {
'sAjaxSource' : path('ajax_purchase_list')
}
})
}}
```
